namespace: "epfl_si"
name: "docker"
version: "0.2.0"
readme: "README.md"
description: Manage “poor man's Kubernetes” setups built out of Docker
authors:
    - "EPFL ISAS-FSD <isas-fsd@groupes.epfl.ch>"
license:
    - "MIT"
tags:
    - docker
repository: "https://github.com/epfl-si/ansible-collection-docker"
dependencies:
  epfl_si.actions: ">=0.1.1"
